In [1]:
#import numpy in python
import numpy as np

In [2]:
#The array object in NumPy is called ndarray.

In [3]:
#We can create a NumPy ndarray object by using the array() function.

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#Use a tuple to create a NumPy array:

arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [5]:
#finding the data type of each array item  

In [6]:
import numpy as np  
a = np.array([1,2,30])
print("Each item is of the type",a.dtype)  

Each item is of the type int32


In [7]:
import numpy as np  
a = np.array([1.0,2.8,30])
print("Each item is of the type",a.dtype)  

Each item is of the type float64


In [8]:
import numpy as np  
a = np.array([5,"fgg","ram"])
print("Each item is of the type",a.dtype)  # <u means unicode

Each item is of the type <U11


# Dimensions in Arrays

#### 0-D Arrays

In [9]:
a= np.array(4)
print(a)
print("dimension: ",a.ndim) 
# |ndim means dimention

4
dimension:  0


#### 1D Array

In [10]:
a= np.array([20,30,40])
print(a)
print("dimension: ",a.ndim) 
# |ndim means dimention

[20 30 40]
dimension:  1


#### 2D Array

In [11]:
a= np.array([[20,30,40],[23,33,22]])
print(a)
print("dimension: ",a.ndim) 
# |ndim means dimention

[[20 30 40]
 [23 33 22]]
dimension:  2


#### 3D Array

In [12]:
a= np.array([[[20,30,40],[20,30,40],[20,30,40]]])
print(a)
print("dimension: ",a.ndim) 
# |ndim means dimention

[[[20 30 40]
  [20 30 40]
  [20 30 40]]]
dimension:  3


In [13]:
#### 4D Array

In [14]:
a= np.array([[[[20,30,40],[20,30,40],[20,30,40]]]])
print(a)
print("dimension: ",a.ndim) 
# |ndim means dimention

[[[[20 30 40]
   [20 30 40]
   [20 30 40]]]]
dimension:  4


## Finding the shape and size of the array

In [15]:
a = np.array([[1,2,3,4,5,6,7]])
print(a)
print("Array Size:",a.size)  
print("Shape:",a.shape)  

[[1 2 3 4 5 6 7]]
Array Size: 7
Shape: (1, 7)


## Reshaping the array objects

In [16]:
a = np.array([[1,2],[3,4],[5,6]])  
print("printing the original array..")  
print(a)  
a=a.reshape(2,3)  
print("printing the reshaped array..")  
print(a)  


printing the original array..
[[1 2]
 [3 4]
 [5 6]]
printing the reshaped array..
[[1 2 3]
 [4 5 6]]


## Slicing in the Array

In [17]:
a = np.array([[1,2],[3,4],[5,6]]) 
print(a[0,1])
print(a[2,0])

2
5


## linspace

In [18]:
 #prints 10 values which are evenly spaced over the given interval 5-15  
a=np.linspace(5,15,10)
print(a)  

[ 5.          6.11111111  7.22222222  8.33333333  9.44444444 10.55555556
 11.66666667 12.77777778 13.88888889 15.        ]


## Finding the maximum, minimum, and sum, Mean of the array elements

In [19]:
a = np.array([1,2,3,10,15,4])  
print("The array:",a)  
print("The maximum element:",a.max())  
print("The minimum element:",a.min())  
print("The sum of the elements:",a.sum())  
print("The sum of the elements:",a.mean()) 

The array: [ 1  2  3 10 15  4]
The maximum element: 15
The minimum element: 1
The sum of the elements: 35
The sum of the elements: 5.833333333333333


## Print zeros 

In [20]:
#  Print zeros 
a=np.zeros(15)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
#print zeros with 2 rows and 3 columns ?
a= np.zeros((2,3))
print(" 2 rows and 3 cols :" )
print(a)



 2 rows and 3 cols :
[[0. 0. 0.]
 [0. 0. 0.]]


## use of eye() diagonal values ?

In [22]:
a= np.eye(4)
print("\ndiaglonal values : ",a)


diaglonal values :  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
a= np.diag([1,2,3,4])
print("\ndiaglonal values : ",a)


diaglonal values :  [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
